title: "Piotr Put, PhD"
author: "Piotr Put"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About me"}
  - {file: "put.pdf", title: "CV"}
  - {title: "Publications", url: "https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=ALUCkoWbFEdPY1kYnblABCJ8z9gAcnb7LTiWJAYDKnYSXVfRBZA1n91QDpY5T9PHqEh63jM1-vONtlTJRfOF-Q&user=7L3drzsAAAAJ"}
  - {file: "README.md", title: "Reading list" }

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "put.piotr@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Aucread"}
  - {title: Twitter, icon: twitter, url: "https://x.com/PutPiotr"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
